### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by kaiko** [bos/hdbc-mysql#12]
After compiling latest (Feb 06, 2014; c2292f0a38) source I get this error:

mysoft.hs: <command line>: can't load .so/.DLL for: /home/me/.cabal/lib/x86_64-linux-ghc-7.8.2/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1-ghc7.8.2.so (/home/me/.cabal/lib/x86_64-linux-ghc-7.8.2/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1-ghc7.8.2.so: undefined symbol: mysql_close)

Compiling process:
runghc Setup configure --user; runghc Setup build; runghc Setup install

Using archlinux and there is MariaDB.

P.S. I hope this library will be updated soon in hackage

**Comment by danchoi** [comment]
It looks like this problem doesn't appear on ghc 7.6, but it appears on 7.8 at least. @snakamura's fix worked for me.

**Comment by NoICE** [comment]
I can confirm that too.
