### ISSUE TITLE
Fails to compile due to "Type Mismatch"

### ISSUE THREAD

**Issue by OutpostNaturalFoods** [bos/hdbc-mysql#15]
MySql fails to install via cabal due to an apparent incorrect type in the statment below:

~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

~$ cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.3 of the Cabal library 

~$ cabal install HDBC-mysql
Resolving dependencies...
[1 of 1] Compiling Main             ( /tmp/HDBC-mysql-0.6.6.1-18304/HDBC-mysql-0.6.6.1/Setup.lhs, /tmp/HDBC-mysql-0.6.6.1-18304/HDBC-mysql-0.6.6.1/dist/setup/Main.o )

/tmp/HDBC-mysql-0.6.6.1-18304/HDBC-mysql-0.6.6.1/Setup.lhs:30:7:
    Couldn't match type ‘IO (Maybe FilePath)’
                  with ‘ProgramSearchPath -> IO (Maybe FilePath)’
    Expected type: IO (Maybe FilePath)
                   -> (Maybe FilePath -> IO (Maybe FilePath))
                   -> ProgramSearchPath
                   -> IO (Maybe FilePath)
      Actual type: IO (Maybe FilePath)
                   -> (Maybe FilePath -> IO (Maybe FilePath)) -> IO (Maybe FilePath)
    In a stmt of a 'do' block:
      mysql_config <- findProgramOnPath "mysql_config" verbosity
    In the expression:
      do { mysql_config <- findProgramOnPath "mysql_config" verbosity;
           mysql_config5 <- findProgramOnPath "mysql_config5" verbosity;
           return (mysql_config `mplus` mysql_config5) }
    In the ‘programFindLocation’ field of a record
Failed to install HDBC-mysql-0.6.6.1
cabal: Error: some packages failed to install:
HDBC-mysql-0.6.6.1 failed during the configure step. The exception was:
ExitFailure 1

**Comment by neuronaut** [comment]
I'm getting the same error with GHC 7.8.4 and Cabal 1.22.0.0. The exact message I get is:

```
Configuring HDBC-mysql-0.6.6.1...
Failed to install HDBC-mysql-0.6.6.1
Build log ( /Users/thomasjones/.cabal/logs/HDBC-mysql-0.6.6.1.log ):
cabal: Error: some packages failed to install:
HDBC-mysql-0.6.6.1 failed during the configure step. The exception was:
user error ('/usr/local/bin/ghc' exited with an error:

/var/folders/lr/57tymqvd4pn35xpxpb357x200000gn/T/HDBC-mysql-0.6.6.1-79268/HDBC-mysql-0.6.6.1/dist/setup/setup.hs:31:7:
Couldn't match type ‘IO (Maybe FilePath)’
with ‘ProgramSearchPath -> IO (Maybe FilePath)’
Expected type: IO (Maybe FilePath)
-> (Maybe FilePath -> IO (Maybe FilePath))
-> ProgramSearchPath
-> IO (Maybe FilePath)
Actual type: IO (Maybe FilePath)
-> (Maybe FilePath -> IO (Maybe FilePath)) -> IO (Maybe FilePath)
In a stmt of a 'do' block:
mysql_config <- findProgramOnPath "mysql_config" verbosity
In the expression:
do { mysql_config <- findProgramOnPath "mysql_config" verbosity;
mysql_config5 <- findProgramOnPath "mysql_config5" verbosity;
return (mysql_config `mplus` mysql_config5) }
In the ‘programFindLocation’ field of a record
)
```

Any help with getting past this would be greatly appreciated!

**Comment by p-alik** [comment]
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library

installation of HDBC-mysql-0.6.6.1 failed.

any help will be greatly appreciated

**Comment by ivanoats** [comment]
Why was this issue closed? What is the resolution? I'm still getting this error today.

**Comment by montonero** [comment]
I still get the installation error on Mac (ghc 7.10.1, cabal 1.22.2.0)

**Comment by backender** [comment]
@montonero same for me, did you find any solution yet?

**Comment by donut** [comment]
I'm also getting this with `stack build`.
`ghc 7.10.2`, `cabal-install 1.22.6.0`

**Comment by topin212** [comment]
This error is still alive on `ghc 7.10.3` with `1.22.6.0` when trying to `cabal install --only-dependencies` in sandbox :)

Any advices on how to fix it?

**Comment by aspidites** [comment]
if you look at this repo's cabal file, you'll see that hdbc-mysql is versioned at 0.6.6.2, where as the version on hackage is 0.6.6.1. As such, I assume the solution is to install from this package, not hackage. With stack, I was able to do this by cloning this repo and adding the following lines to my stack.yaml:

```yaml
packages:
- '../hdbc-mysql'
extra-deps:
- HDBC-mysql-0.6.6.2
```
